### ISSUE TITLE
Limit posts results to content type blog

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#17]
Our API might deliver other content types in the future, as mentioned on our [developer site](https://developer.twingly.com/resources/search/#response):

> * post - the root element for a blog post
  * contentType - currently, the only available type is blog

In our other clients we went with the route to ignore non blog content types to make it easier for us to change the API in the future. In the Java client we have the following fixture, and corresponding test: https://github.com/twingly/twingly-search-api-java/blob/73b64d64418dda117e922f49e957ea0877aec9f6/src/test/resources/com/twingly/search/client/valid_non_blog_result.xml

**Comment by amironoff** [comment]
Honestly, that seems kinda awkward. Why don't you introduce an API request argument, named 'contentType', that will filter out extra content types _in case there actually are several_ ?

Given the solution you're proposing, what happens if the server says 'I returned 20 results in this page', I legitimately set up a _for loop_ over 20 items, but there are just 3 posts with contentType='blog'?

P.S. it would be much better to just use api versioning instead of adding dummy xml elements & attributes 'necessary in the future'.

**Comment by amironoff** [comment]
In case there are multiple contentTypes, your current libraries will also page awkwardly, when using the [sliding window technique](https://developer.twingly.com/resources/search/#pagination). E.g. which is the last post in this case? How come numberOfMatchesReturned doesn't match result.Posts?

**Comment by amironoff** [comment]
My suggestion is that you opt for API versioning, instead of filtering on the client side.

**Comment by walro** [comment]
I think you have some very valid points, let me try to explain why we are asking.

The original intention of the API was to deliver more than just blog posts, for example forum posts. The end-user would perform a search and get search hits from mixed sources.

Right now, as you know, we only deliver the blog content type through the API but if we want to start delivering a new content type we a few options:

* Deliver the type in a completely new API, using a completely different client
  * Might be the route we'll go, but we don't know today so let's not dig deeper here :)
* Use parameters to limit the search for specific content types
  * Should work, but I don't think that's the best route to go. We want to be able to deliver more than just one type per round-trip
* Use versioning, current version (2) just delivers blogs, next version (3) starts delivering the new type
  * This is what we'll likely do, as you suggested, but let me try to explain it more in detail below
* Don't do anything of the above, continue using the same API and just start delivering mixed contents
  * Obviously a bad idea as it will likely break implementations for current customers which are not using our official clients

So let's assume we'll go with the versioning and mixed content route. We will need to take `contentType` into account as the elements may differ (`blogName` won't make sense for instance). What we are looking for is code that will require the least amount of change when we are introducing a new content type (and version) – we need it to "just work" for at least blogs right off the bat. We thought that if we explicitly already started to care of the blog contentType there would be less work when we introduce a new one.

Another reason to do it here, is simply because all our other clients already do it. I don't really like that argument, but it's still an argument ;-).

Does that make sense?

**Comment by amironoff** [comment]
Hi @walro. Thanks for describing your line of thinking. The change you're requesting will not lead you to where you want to be :) It will not "just work" with a new API, because it breaks iterating the result collection. So, some of your customers will get nasty surprises if you rely on this mechanism. There's no free lunch in this case.

The way to implement your use case AND achieve your goals/not piss off your customers is:

1. Don't do any filtering on the client side;
2. After you implement API changes, release them as version v3. Use [request/accept headers or specify version via url, e.g. 'apy.twingly.com/v3/'](https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/), as you prefer; If version is not specified, use v2 as default.
3. Update the client to use v3 and send a contentType='blog' filter to the API.(do server-side content filtering, instead of client-side)

If you'd like to step into same puddle as others with the .NET client too, sure I can implement that. However, if you fancy some advice, I strongly recommend against.

**Comment by walro** [comment]
Hey,

I think we want the same things, but seem to be able to communicate it properly 😄 .

When/if we add new content types in the API, we will add a new API version. The current version will never start delivering other things than blogs. So changing the code to filter at this point will never really matter from the eyes of the end-user.

So let's talk about our new API version. We might (unknown territory at this point) want it to be able to handle two cases: mixed content types (default) and server-side filtering on content type. We will obviously ship a new API clients capable of handling this. Why we are asking for "client-side filtering" at this point is just to make our lives a bit easier in the future. There are already some boiler-plate for handling the blog type and you could (if you can live with the quirks, i.e. the iterating problem) use the older versions of the clients against the newer APIs.

**Comment by amironoff** [comment]
Yeah, we totally agree on everything, except on the impact of client-side filtering :D One thing I learned about the future is that by the time you arrive there, everything changes. So the best way to prepare for it is just make sure that your code is easy to change. Adding functionality that _may be needed in the future, but we don't know if it will_ usually doesn't work. 

Anyway, here's the changeset - https://github.com/amironoff/twingly-search-api-dotnet/commit/d69bf50c9f1ed60f317573e4fa32150a087f4817

**Comment by walro** [comment]
> So the best way to prepare for it is just make sure that your code is easy to change. Adding functionality that may be needed in the future, but we don't know if it will usually doesn't work.

I agree, and I admire that you took your stand. We opted for consistency for our clients this time, if we had done this client first things would probably have been different. Thanks for complying anyway.
