### ISSUE TITLE
Make example read API key from environment

### ISSUE THREAD

**Issue by twingly-mob** [amironoff/twingly-search-api-dotnet#2]
After #1 is solved:

It would be easier to run the examples if the API key was [read from the environment variable](https://msdn.microsoft.com/en-us/library/77zkk0b6(v=vs.110).aspx) `TWINGLY_SEARCH_KEY` (we use this environment variable for our other clients).

In the example code it could look like:

```cs
string apiKey = Environment.GetEnvironmentVariable("TWINGLY_SEARCH_KEY");

// instantiate the client with the key according to suggestion in issue 1
```

**Comment by amironoff** [comment]
Although this is something out of initial scope, I'll add this as a bonus. 

BTW, Instead of environment variables, the more common practice I've seen is to store sensitive configuration either in machine.config or external encrypted configuration files. On the other hand, cloud services are a viable use case for env. vars, so I'll agree with you.

**Comment by amironoff** [comment]
Renamed FileConfiguration to LocalConfiguration and changed it to fallback to Environment Variables.

**Comment by twingly-mob** [comment]
👍
